# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='exam.Quote')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='exam.User')),
            ],
        ),
    ]
