# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exam.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_quotes',
            field=models.ManyToManyField(default=None, related_name='favorite_quotes', to='exam.Quote'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
