# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20180203_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_quotes',
            field=models.ManyToManyField(related_name='favorite_quotes', to='exam.Quote'),
        ),
    ]
