# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20180203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
